[package]
name = "zero-raf-host"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
zero-raf-methods = { path = "../methods" }
zero-raf-core = { path = "../core" }
risc0-zkvm = { version = "0.15", default-features = false, features = ["metal"] }