[package]
name = "zero-raf-host"
version = "0.1.0"
edition = "2023"

[dependencies]
methods = { path = "../methods" }
csv = "1.1"
regex = "1.6.0"
risc0-zkvm = "0.14.0"
zero-raf-core = { path = "../core" }
