[package]
name = "zero-raf-methods"
version = "0.1.0"
edition = "2021"


[build-dependencies]
risc0-build = { git = "https://github.com/risc0/risc0.git", rev = "84528d31c0efad566e585aa04a83d6692b32bd16" }

[package.metadata.risc0]
methods = ["guest"]
