[package]
name = "zero-raf-methods"
version = "0.1.0"
edition = "2021"


[build-dependencies]
risc0-build = { git = "https://github.com/risc0/risc0.git", rev = "6fb72df1284c0cf0a516dd87af193256d1baec81" }

[package.metadata.risc0]
methods = ["guest"]
